### ISSUE TITLE
Any possibility of adding communication option via SPI or I2C?

### ISSUE THREAD

**Issue by rtek1000** [leech001/gps#1]
Hi, great job!

Any possibility to add communication option via SPI and I2C?

I found it interesting to use SPI or I2C to make it a little more difficult to falsify the GPS signal, in the case of tracking devices left in lending mode on clients.

The idea is to need the GPS signal to update the RTC and also to generate a product key for periodic unlocking.

Thank you.

> 1.12.1 UART
> NEO-6 modules include one configurable UART interface for serial communication (for information about configuration see section 1.15).

> 1.12.2 USB
> NEO-6 modules provide a USB version 2.0 FS (Full Speed, 12Mbit/s) interface as an alternative to the UART. The pull-up resistor on USB_DP is integrated to signal a full-speed device to the host. The VDDUSB pin supplies the USB interface. u-blox provides a Microsoft® certified USB driver for Windows XP, Windows Vista and Windows 7 operating systems.

> 1.12.3 Serial Peripheral Interface (SPI)
> The SPI interface allows for the connection of external devices with a serial interface, e.g. serial flash to save configuration and AssistNow Offline A-GPS data or to interface to a host CPU. The interface can be operated in master or slave mode. In master mode, one chip select signal is available to select external slaves. In slave mode a single chip select signal enables communication with the host.
> The maximum bandwidth is 100kbit/s.

> 1.12.4 Display Data Channel (DDC)
> The I2C compatible DDC interface can be used either to access external devices with a serial interface EEPROM or to interface with a host CPU. It is capable of master and slave operation. The DDC interface is I2C Standard Mode compliant. For timing parameters consult the I2C standard.
> The DDC Interface supports serial communication with u-blox wireless modules. See the specification of the applicable wireless module to confirm compatibility.
> The maximum bandwidth is 100kbit/s.

https://www.u-blox.com/sites/default/files/products/documents/NEO-6_DataSheet_(GPS.G6-HW-09005).pdf

**Comment by leech001** [comment]
Hi!
Probably not, since I use the GPS module directly to determine the coordinates through the ready modules. And on them by default is not divorced interface other than UART.
Also because of the size went to the module [https://aliexpress.ru/item/4000217184109.html?spm=a2g0s.9042311.0.0.264d33edxzu92q&_ga=2.45341988.1253356775.1605291228-1518822108.1603610083](https://aliexpress.ru/item/4000217184109.html?spm=a2g0s.9042311.0.0.264d33edxzu92q&_ga=2.45341988.1253356775.1605291228-1518822108.1603610083) which does not have a different interface from UART.
